version: '3.1' 
services:

  
  php:
    build: ./docker-php 
    working_dir: /var/www/laravel 
    volumes:
      - ./www:/var/www/laravel

  nginx:
    build: ./docker-nginx
    working_dir: /var/www/laravel 
    volumes_from:
      - php 
    ports:
      - 80:80 
      

  
  database:
    image: mariadb:10.5.9
    volumes:
      - ./mysql/data:/var/lib/mysql 
    
    environment:
      - MYSQL_DATABASE=ischooltec
      - MYSQL_ROOT_PASSWORD=86jnkVW4PY2L
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=iM96JrBIkhgb
    ports:
      - 3306:3306 

  composer: 
    build: ./docker-php 
    working_dir: /var/www/laravel
    volumes_from:
      - php
    command: "composer install" 


  
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminis
    ports:
        - 8080:80
    environment:
        - UPLOAD_LIMIT=1G
        - PMA_HOST=database
        - PMA_ARBITRARY=1
    restart: always
    depends_on:
        - database
        
